name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-build-test:
    name: Check, Build, and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          substituters = https://hydra.iohk.io
        nix_path: "nixpkgs=channel:nixos-unstable"
    - uses: cachix/cachix-action@v10
      with:
        name: cachix-action
    - run: nix-build ci.nix -A build
    - run: nix-shell --run "echo OK"
